config/routes.rb
Rails.application.routes.draw do
root "jobs#index"
get '/garysguide' => 'jobs#garysguide'
get '/glassdoor' => 'jobs#glassdoor'
get '/indeed' => 'jobs#indeed'

end

app/models/job.rb
class Job < ActiveRecord::Base
  # attr_accessor :title, :company, :link
  # validates :title, :company, :link presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.all
  end

  def garysguide
    @jobs = Job.where origin: "GarysGuide"
  end

  def glassdoor
    @jobs = Job.where origin: "Glassdoor"
  end

  def indeed
    @jobs = Job.where origin: "Indeed"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/garysguide.html.erb
<h1><span style="color:#66ff99; font-size:100px;"><%= @jobs.count %></span> Technical Product/Project Management Gigs from <%= @jobs.first.origin %></h1>

<!-- <table align="center"> -->
<div id="main_container">
  <% @jobs.each do |job| %>
      <div class="job">
        <div class="text">
          <b class="ellipsis"><%= job.company %></b>
          <div>
            <%= link_to job.title, job.link, class: 'myButton', target: '_blank' %>
          </div>
        </div>
      </div>
  <% end %>
  <div style="clear:both;"></div>
</div>
<!-- </table> -->

app/views/jobs/glassdoor.html.erb
<h1><span style="color:#66ff99; font-size:100px;"><%= @jobs.count %></span> Technical Product/Project Management Gigs from <%= @jobs.first.origin %></h1>

<!-- <table align="center"> -->
<div id="main_container">
  <% @jobs.each do |job| %>
      <div class="job">
        <div class="text">
          <b class="ellipsis"><%= job.company %></b>
          <div>
            <%= link_to job.title, job.link, class: 'myButton', target: '_blank' %>
          </div>
        </div>
      </div>
  <% end %>
  <div style="clear:both;"></div>
</div>
<!-- </table> -->

app/views/jobs/indeed.html.erb
<h1><span style="color:#66ff99; font-size:100px;"><%= @jobs.count %></span> Technical Product/Project Management Gigs from <%= @jobs.first.origin %></h1>

<!-- <table align="center"> -->
<div id="main_container">
  <% @jobs.each do |job| %>
      <div class="job">
        <div class="text">
          <b class="ellipsis"><%= job.company %></b>
          <div>
            <%= link_to job.title, job.link, class: 'myButton', target: '_blank' %>
          </div>
        </div>
      </div>
  <% end %>
  <div style="clear:both;"></div>
</div>
<!-- </table> -->

app/views/jobs/index.html.erb
<h1><span style="color:#66ff99; font-size:100px;"><%= @jobs.count %></span> Technical Product/Project Management Gigs</h1>

<!-- <table align="center"> -->
<div id="main_container">
  <% @jobs.each do |job| %>
      <div class="job">
        <div class="text">
          <b class="ellipsis"><%= job.company %></b>
          <div>
            <%= link_to job.title, job.link, class: 'myButton', target: '_blank' %>
          </div>
        </div>
      </div>
  <% end %>
  <div style="clear:both;"></div>
</div>
<!-- </table> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JobScraper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to "All", root_path %> |
<%= link_to "GarysGuide", garysguide_path %> |
<%= link_to "Glassdoor", glassdoor_path %> |
<%= link_to "Indeed", indeed_path %>

<%= yield %>

</body>
</html>